using System.Data;
using System.Threading.Tasks;

namespace LegacySql.Legacy.Data.ConsumerCommandContracts
{
    public interface IProductStore
    {
        Task<int> Create(string brand,
            string workName,
            int productTypeId,
            string subtype,
            string productCategory,
            string manufacture,
            int? manufactureId,
            string vendorCode,
            string nomenclatureBarcode,
            string nameForPrinting,
            int productCountryId,
            int brandCountryId,
            double? weight,
            double? volume,
            byte? guarantee,
            byte? guaranteeIn,
            string unit,
            decimal vat,
            bool? isImported,
            string nomenclatureCode,
            bool? isProductIssued,
            bool? isDistribution,
            bool? scanMonitoring,
            bool? scanHotline,
            bool? game,
            bool manualRrp,
            bool notInvolvedInPricing,
            byte monitoring,
            bool price,
            bool? markdown,
            string manufactureSiteLink,
            byte? currencyId,
            string managerNickName,
            int? managerId,
            double? height,
            double? width,
            double? depth,
            IDbTransaction transaction);
        Task Update(int productCode,
            string brand,
            string workName,
            int productTypeId,
            string subtype,
            string productCategory,
            string manufacture,
            int? manufactureId,
            string vendorCode,
            string nomenclatureBarcode,
            string nameForPrinting,
            int productCountryId,
            int brandCountryId,
            double? weight,
            double? volume,
            byte? guarantee,
            byte? guaranteeIn,
            string unit,
            decimal vat,
            bool? isImported,
            string nomenclatureCode,
            bool? isProductIssued,
            bool? isDistribution,
            bool? scanMonitoring,
            bool? scanHotline,
            bool? game,
            bool manualRrp,
            bool notInvolvedInPricing,
            byte monitoring,
            bool price,
            bool? markdown,
            string manufactureSiteLink,
            byte? currencyId,
            string managerNickName,
            int? managerId,
            double? height,
            double? width,
            double? depth,
            IDbTransaction transaction);

        Task InsertParameter(int productId, int categoryId, int categoryParamId, IDbTransaction transaction);
        Task UpdateParameter(int id, int productId, int categoryId, int categoryParamId, IDbTransaction transaction);
        Task UpdateDescriptions(int productId, int languageId, string description, IDbTransaction transaction);

    }
}
